version: 0.2
phases:
   pre_build:
      commands:
      - echo "Entered the pre-build phase on `date` "
   build:
      commands:
      - echo "Entered build phase"
      - mvn clean install
      - echo "Build Completed on `date` "
   post_build:
      commands:
      - echo "Entered the post-build phase"
artifacts:
   files:
   - target/loan.jar